services:
  nginx:
    image: nginx:latest
    volumes:
      - /path/to/your/wp-content/:/var/www/html # Mount Wordpress location
      - /path/to/your/localhost.crt:/etc/ssl/certs/localhost.crt  # Mounting the certificate
      - /path/to/your/localhost.key:/etc/ssl/private/localhost.key  # then the key
      - /path/to/your/nginx.conf:/etc/nginx/conf.d/default.conf  # Mounting custom nginx.conf
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mysql:lts
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #set these private .env vars
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    user: 502:502
    ports:
      - 8080:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      
    volumes:
      - type: bind
        source: /path/to/your/wp-content/
        target: /var/www/html/wp-content
      - /path/to/your/php.ini>:/usr/local/etc/php/conf.d/custom.ini
 
volumes:
  db_data: {}
